package model

type TingShuNovel struct {
	LogoURL               string             `json:"logoUrl"`
	ColumnName            string             `json:"columnName"`
	IsSubscribe           int                `json:"isSubscribe"`
	SubscribeID           interface{}        `json:"subscribeId"`
	ProviderCode          int                `json:"providerCode"`
	ProviderName          string             `json:"providerName"`
	ColumnID              string             `json:"columnId"`
	Collect               int                `json:"collect"`
	Descriptions          string             `json:"descriptions"`
	ListenNum             int                `json:"listenNum"`
	ReplyNum              int                `json:"replyNum"`
	Anchorpersons         string             `json:"anchorpersons"`
	DiscountedPrice       interface{}        `json:"discountedPrice"`
	OriginalPrice         interface{}        `json:"originalPrice"`
	DiscountedPriceV      interface{}        `json:"discountedPriceV"`
	OriginalPriceV        interface{}        `json:"originalPriceV"`
	IsExpired             int                `json:"isExpired"`
	ExpireTime            int                `json:"expireTime"`
	IsPurchased           int                `json:"isPurchased"`
	NeedPay               int                `json:"needPay"`
	AnchorpersonList      []AnchorpersonList `json:"anchorpersonList"`
	ListenType            int                `json:"listenType"`
	ExpireDate            interface{}        `json:"expireDate"`
	AlbumCollection       interface{}        `json:"albumCollection"`
	DescriptionSimple     string             `json:"descriptionSimple"`
	ColumnAnchorInfo      ColumnAnchorInfo   `json:"columnAnchorInfo"`
	Expire                int                `json:"expire"`
	ExpireStart           string             `json:"expireStart"`
	ExpireEnd             string             `json:"expireEnd"`
	IsOver                int                `json:"isOver"`
	ContentType           int                `json:"contentType"`
	SongNeedPay           int                `json:"songNeedPay"`
	ContainAuditionSong   int                `json:"containAuditionSong"`
	HadPurchasedSong      int                `json:"hadPurchasedSong"`
	NotPurchasedSongCount int                `json:"notPurchasedSongCount"`
	Pubstate              int                `json:"pubstate"`
	PosterInfo            PosterInfo         `json:"posterInfo"`
	ChechStatus           int                `json:"chechStatus"`
	HistoryPo             HistoryPo          `json:"historyPo"`
	ForeverHear           int                `json:"foreverHear"`
	CanLode               int                `json:"canLode"`
	CommentStatus         int                `json:"commentStatus"`
	ShareFreeNum          int                `json:"shareFreeNum"`
	AtypeInfo             []AtypeInfo        `json:"atypeInfo"`
	UpdateTime            string             `json:"updateTime"`
	Type                  string             `json:"type"`
	SortType              int                `json:"sortType"`
	CoverLong             interface{}        `json:"coverLong"`
	CoverSquare           interface{}        `json:"coverSquare"`
	IsVip                 int                `json:"isVip"`
	ShareURL              string             `json:"shareUrl"`
	SubscribeNum          int                `json:"subscribeNum"`
	OwnerNickName         string             `json:"ownerNickName"`
	OwnerIcon             string             `json:"ownerIcon"`
	TotalPage             int                `json:"totalPage"`
	Count                 int                `json:"count"`
	CurrentPage           int                `json:"currentPage"`
	PerPage               int                `json:"perPage"`
	PlayList              []PlayList         `json:"con"`
	Rt                    int                `json:"rt"`
	Des                   string             `json:"des"`
}
type AnchorpersonList struct {
	ID                   string      `json:"id"`
	AnchorpersonID       string      `json:"anchorpersonId"`
	AnchorpersonName     string      `json:"anchorpersonName"`
	AnchorpersonPic      string      `json:"anchorpersonPic"`
	BgURL                interface{} `json:"bgUrl"`
	FansNickName         interface{} `json:"fansNickName"`
	FansNum              int         `json:"fansNum"`
	IsFollow             int         `json:"isFollow"`
	LevelIcon            interface{} `json:"levelIcon"`
	IfHasLive            int         `json:"ifHasLive"`
	BroadcastModel       interface{} `json:"broadcastModel"`
	InteractiveModelType interface{} `json:"interactiveModelType"`
	AnchorzoneModelType  interface{} `json:"anchorzoneModelType"`
	BroadcastName        interface{} `json:"broadcastName"`
	BroadcastID          interface{} `json:"broadcastId"`
	SwitchStatus         interface{} `json:"switchStatus"`
	FocusIcon            interface{} `json:"focusIcon"`
	UnfocusIcon          interface{} `json:"unfocusIcon"`
	IsAnchorPerson       string      `json:"isAnchorPerson"`
	DownDes              string      `json:"downDes"`
	HostTotal            int         `json:"hostTotal"`
	DescriptionSimple    interface{} `json:"descriptionSimple"`
	ShareURL             interface{} `json:"shareUrl"`
	RoleNameForAlbum     string      `json:"roleNameForAlbum"`
	LiveStatus           int         `json:"liveStatus"`
	LiveID               interface{} `json:"liveId"`
	IsPugcAnchor         int         `json:"isPugcAnchor"`
	Accid                interface{} `json:"accid"`
	AuthType             int         `json:"authType"`
}
type ColumnAnchorInfo struct {
	ID                   string      `json:"id"`
	AnchorpersonID       string      `json:"anchorpersonId"`
	AnchorpersonName     string      `json:"anchorpersonName"`
	AnchorpersonPic      string      `json:"anchorpersonPic"`
	BgURL                interface{} `json:"bgUrl"`
	FansNickName         interface{} `json:"fansNickName"`
	FansNum              int         `json:"fansNum"`
	IsFollow             int         `json:"isFollow"`
	LevelIcon            interface{} `json:"levelIcon"`
	IfHasLive            int         `json:"ifHasLive"`
	BroadcastModel       interface{} `json:"broadcastModel"`
	InteractiveModelType interface{} `json:"interactiveModelType"`
	AnchorzoneModelType  interface{} `json:"anchorzoneModelType"`
	BroadcastName        interface{} `json:"broadcastName"`
	BroadcastID          interface{} `json:"broadcastId"`
	SwitchStatus         interface{} `json:"switchStatus"`
	FocusIcon            interface{} `json:"focusIcon"`
	UnfocusIcon          interface{} `json:"unfocusIcon"`
	IsAnchorPerson       string      `json:"isAnchorPerson"`
	DownDes              string      `json:"downDes"`
	HostTotal            int         `json:"hostTotal"`
	DescriptionSimple    string      `json:"descriptionSimple"`
	ShareURL             interface{} `json:"shareUrl"`
	RoleNameForAlbum     string      `json:"roleNameForAlbum"`
	LiveStatus           int         `json:"liveStatus"`
	LiveID               interface{} `json:"liveId"`
	IsPugcAnchor         int         `json:"isPugcAnchor"`
	Accid                interface{} `json:"accid"`
	AuthType             int         `json:"authType"`
}
type PosterInfo struct {
	ID            int64       `json:"id"`
	Type          int         `json:"type"`
	ImgURL        string      `json:"imgUrl"`
	Title         string      `json:"title"`
	Describe      string      `json:"describe"`
	Source        interface{} `json:"source"`
	Color         interface{} `json:"color"`
	CreateTime    interface{} `json:"createTime"`
	ChannelImgURL interface{} `json:"channelImgUrl"`
	ContentType   int         `json:"contentType"`
	Description   interface{} `json:"description"`
}
type HistoryPo struct {
	ID               interface{} `json:"id"`
	ColumnID         int64       `json:"columnId"`
	Price            interface{} `json:"price"`
	NeedPay          interface{} `json:"needPay"`
	SongNeedPay      interface{} `json:"songNeedPay"`
	StartTime        interface{} `json:"startTime"`
	EndTime          interface{} `json:"endTime"`
	Operation        interface{} `json:"operation"`
	Reviewer         interface{} `json:"reviewer"`
	States           interface{} `json:"states"`
	ReviewerTime     interface{} `json:"reviewerTime"`
	ReviewerReason   interface{} `json:"reviewerReason"`
	Note             interface{} `json:"note"`
	Charge           interface{} `json:"charge"`
	ApplicationTime  interface{} `json:"applicationTime"`
	Expiretime       interface{} `json:"expiretime"`
	Sharefreenum     interface{} `json:"sharefreenum"`
	OldPrice         interface{} `json:"oldPrice"`
	OldCharge        interface{} `json:"oldCharge"`
	PromotionType    int         `json:"promotionType"`
	PromotionStaTime interface{} `json:"promotionStaTime"`
	PromotionEndTime interface{} `json:"promotionEndTime"`
	PlanShowNum      interface{} `json:"planShowNum"`
	PromotionPrice   interface{} `json:"promotionPrice"`
}
type AtypeInfo struct {
	CategoryName string `json:"categoryName"`
	CategoryID   int    `json:"categoryId"`
}
type PlayList struct {
	ID                 string      `json:"id"`
	Name               string      `json:"name"`
	Index              int         `json:"index"`
	ProviderName       string      `json:"providerName"`
	PlayURL            string      `json:"playUrl"`
	PlayURLHigh        string      `json:"playUrlHigh"`
	Artist             interface{} `json:"artist"`
	ListenNum          int         `json:"listenNum"`
	ReplyNum           int         `json:"replyNum"`
	LogoURL            string      `json:"logoUrl"`
	SongLogo           interface{} `json:"songLogo"`
	IsCollect          int         `json:"isCollect"`
	Anchorperson       interface{} `json:"anchorperson"`
	AnchorpersonList   interface{} `json:"anchorpersonList"`
	ColumnID           string      `json:"columnId"`
	Duration           string      `json:"duration"`
	ColumnName         interface{} `json:"columnName"`
	ColumnLogo         interface{} `json:"columnLogo"`
	DescriptionSimple  interface{} `json:"descriptionSimple"`
	IfDownload         int         `json:"ifDownload"`
	IsPraise           int         `json:"isPraise"`
	PraiseCount        interface{} `json:"praiseCount"`
	IsAudition         int         `json:"isAudition"`
	IsExpired          int         `json:"isExpired"`
	IsPurchased        int         `json:"isPurchased"`
	NeedPay            int         `json:"needPay"`
	ListenType         int         `json:"listenType"`
	PromotionType      int         `json:"promotionType"`
	ShareFreeNum       interface{} `json:"shareFreeNum"`
	CreateTime         string      `json:"createTime"`
	PublishTime        interface{} `json:"publishTime"`
	DownloadURL        string      `json:"downloadUrl"`
	FileSize           string      `json:"fileSize"`
	PlayURLMedium      string      `json:"playUrlMedium"`
	CoverLong          interface{} `json:"coverLong"`
	CoverSquare        interface{} `json:"coverSquare"`
	SDescription       string      `json:"sDescription"`
	IsVip              int         `json:"isVip"`
	ShareURL           interface{} `json:"shareUrl"`
	Expire             int         `json:"expire"`
	ExpireStart        interface{} `json:"expireStart"`
	ExpireEnd          interface{} `json:"expireEnd"`
	SubscribeTime      interface{} `json:"subscribeTime"`
	StartTime          interface{} `json:"startTime"`
	EndTime            interface{} `json:"endTime"`
	ContentType        int         `json:"contentType"`
	AlbumContentType   int         `json:"albumContentType"`
	AlbumDescription   interface{} `json:"albumDescription"`
	ColumnPubState     int         `json:"columnPubState"`
	SongPubState       int         `json:"songPubState"`
	ColumnCheckStatus  int         `json:"columnCheckStatus"`
	SongCheckStatus    int         `json:"songCheckStatus"`
	SongDeleteStatus   interface{} `json:"songDeleteStatus"`
	SongVirtualPrice   float64     `json:"songVirtualPrice"`
	SongNeedPay        int         `json:"songNeedPay"`
	IsSongPurchased    int         `json:"isSongPurchased"`
	SongID             interface{} `json:"songId"`
	TopState           interface{} `json:"topState"`
	ShareLogo          interface{} `json:"shareLogo"`
	RadioLogo          interface{} `json:"radioLogo"`
	PortraitPath       interface{} `json:"portraitPath"`
	HorizontalPath     interface{} `json:"horizontalPath"`
	VehiclePath        interface{} `json:"vehiclePath"`
	TopPath            interface{} `json:"topPath"`
	NewsContentURL     interface{} `json:"newsContentUrl"`
	RadioID            interface{} `json:"radioId"`
	RadioName          interface{} `json:"radioName"`
	HeadLogo           interface{} `json:"headLogo"`
	BackColor          interface{} `json:"backColor"`
	Tags               interface{} `json:"tags"`
	ClassificationPath interface{} `json:"classificationPath"`
	ClassificationName interface{} `json:"classificationName"`
	ClassificationID   interface{} `json:"classificationId"`
	NewsSource         interface{} `json:"newsSource"`
	TagList            interface{} `json:"tagList"`
	Announcer          interface{} `json:"announcer"`
	Editor             interface{} `json:"editor"`
	UserNewsWeight     interface{} `json:"userNewsWeight"`
	PlayURLEncode      string      `json:"playUrlEncode"`
	PlayURLHighEncode  string      `json:"playUrlHighEncode"`
	EncodeStatus       int         `json:"encodeStatus"`
	ResourceType       int         `json:"resourceType"`
	PlayIndex          int         `json:"playIndex"` //集数
}
